---
name: CI

on:
  push:
    workflow_distpatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: echo "example"

  lint-all:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false


  lint-all:
    name: Static Code Analysis Tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

  